### ISSUE TITLE
Unable to render SRT subtitles

### ISSUE THREAD

**Issue by adworacz** [vapoursynth/subtext#11]
While testing recently, I found that SRT subtitles are not rendered at all using this plugin. Taking the same file and converting it to ASS using ffmpeg and then rendering again using this plugin works like a charm.

Example script:
```
import vapoursynth as vs

core = vs.core

clip = core.std.BlankClip(width=720, height=304, length=2000)
clip = clip.sub.TextFile("./subs-short.srt")

clip.set_output()
```

Use the attached file (rename to srt as appropriate, Github only allows txt files). You'll see a black clip rendered with no text.

[subs-short.txt](https://github.com/vapoursynth/subtext/files/9894139/subs-short.txt)

**Comment by myrsloik** [comment]
Fixed, broke due to ffmpeg behavior changes

**Comment by adworacz** [comment]
Awesome, thank you!
